/* No external scripts, analytics, fonts, or remote storage. */
'use strict';
const C=window.RadarCore,seed=window.RADAR_SEED,$=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,title='打开原文 ↗')=>C.safeURL(url)?`<a href="${esc(C.safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`:'';
const KEY='econ-radar-private-jobs-v1';let state={version:1,jobs:[],events:[],consultations:[],hidden:[],keywords:'经济 金融 财政 计量 劳动 社会保障 公共管理 博士后'},tab='overview',query='',filter='',page=1,feed={items:[],runs:[]},sources=[],snapshot=false,online=false,editing=null,dirtySources=false,storageBroken=false;
try{const stored=localStorage.getItem(KEY);if(stored)state={version:1,...C.backup(stored)};}catch(e){storageBroken=true;$('#storage-warning').hidden=false;$('#storage-warning').textContent='浏览器存储不可用或原有数据无法读取。为保护旧记录，已暂停写入。请先导出备份；不要清理浏览器数据。错误：'+e.message;}
function persist(next){if(storageBroken){toast('存储不可用，未保存。请先导出备份并检查浏览器设置。');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));state=next;return true;}catch(e){$('#storage-warning').hidden=false;$('#storage-warning').textContent='保存失败：'+e.message+'。请导出备份，当前修改尚未保存。';toast('保存失败，请检查存储空间');return false;}}
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4500);}
function download(name,text,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function exportBackup(){download('econ-radar-求职备份-'+C.today()+'.json',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2));toast('备份已导出，请妥善保存');}
function switchTab(t){tab=t;query='';filter='';page=1;render();window.scrollTo(0,0);}
const meta={overview:['我的日程','今天的安排、近期截止与下一步跟进。'],consultations:['咨询记录','保留交流原意，把需要跟进的事项加入日程。'],conferences:['会议信息','浏览会议与征稿，选择需要准备的机会。'],jobs:['我的投递','这里仅记录你自己的申请；每一次推进都有迹可循。'],feed:['招聘线索','自动发现标题线索，打开原文核实后再加入申请。'],references:['历史参考库','从前人的表格出发，建立自己的目标清单。'],resources:['模板与经验','原始资料随包保存，供你按需查阅。'],settings:['来源与备份','管理招聘来源，让记录随时可以带走。']};
function stats(){const tasks=C.tasks(state.jobs);return `<div class="stats">${[['我的申请',state.jobs.length,'累计建立的目标'],['进行中',state.jobs.filter(j=>!['已获 Offer','已结束'].includes(j.stage)).length,'准备、投递与面试'],['待处理事项',tasks.length,'未来 14 天及已逾期'],['已获 Offer',state.jobs.filter(j=>j.stage==='已获 Offer').length,'已收到的录用机会']].map(([a,b,c])=>`<div class="stat"><small>${a}</small><strong>${b}</strong><em>${c}</em></div>`).join('')}</div>`;}
function toolbar(options,placeholder){return `<div class="toolbar"><input id="search" aria-label="搜索" placeholder="${placeholder}" value="${esc(query)}">${options?`<select id="filter" aria-label="筛选"><option value="">全部</option>${options.map(s=>`<option ${filter===s?'selected':''}>${esc(s)}</option>`).join('')}</select>`:''}</div>`;}
function matches(x){return !query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase());}
function deadline(s){const d=C.days(s);return d===null?'<span class="muted">未确认</span>':`<span class="pill ${d<0?'red':d<=7?'warn':''}">${esc(s)}</span><span class="muted">${d<0?'已过 '+(-d)+' 天':d===0?'今天截止':'剩余 '+d+' 天'}</span>`;}
function jobs(){const rows=state.jobs.filter(j=>matches(j)&&(!filter||j.stage===filter)).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));return toolbar(C.stages,'搜索学校、岗位、方向或备注…')+`<div class="toolbar"><button id="export-csv">导出 Excel 可读的 CSV</button><button data-import>导入 CSV / 备份</button><span class="muted">${rows.length} 条申请</span></div>`+(rows.length?`<div class="table-wrap"><table><thead><tr><th>学校 / 岗位</th><th>阶段</th><th>截止日期</th><th>材料与推荐信</th><th>下一步</th><th>操作</th></tr></thead><tbody>${rows.map(j=>`<tr><td><strong>${esc(j.school)}</strong><span class="muted">${esc([j.department,j.role].filter(Boolean).join(' · '))}</span><span class="pill ${j.verified?'':'warn'}">${j.verified?'已人工核实':'待核实'}</span> ${j.priority==='优先'?'<span class="pill">优先</span>':''}</td><td>${esc(j.stage)}</td><td>${deadline(j.deadline)}</td><td>${j.materials.length} / ${C.materials.length} 项材料<span class="muted">推荐信：${esc(j.referenceState)}</span></td><td>${j.followupAt?esc(j.followupAt):'<span class="muted">未设跟进日</span>'}<span class="muted">${esc(j.notes.slice(0,60))}</span></td><td><button data-edit="${esc(j.id)}">编辑 / 跟进</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="panel empty"><strong>${state.jobs.length?'没有匹配的申请':'你的投递清单还是空的'}</strong>新建申请，或从历史参考库加入目标。</div>`);}
function references(){const rows=seed.references.filter(r=>matches(r)&&(!filter||r.source.startsWith(filter+':'))),pages=Math.max(1,Math.ceil(rows.length/20));page=Math.min(page,pages);return `<div class="notice">这些记录包含前人的历史投递结果和旧招聘条件，仅供选校参考。“建立申请”只带入学校、院系、岗位与链接，日期和个人进度需重新填写。</div>`+toolbar([...new Set(seed.references.map(r=>r.source.split(':')[0]))],'搜索学校、方向、推荐信或原表内容…')+`<div class="table-wrap"><table><thead><tr><th>学校 / 机构</th><th>院系 / 方向 / 岗位</th><th>出处</th><th>操作</th></tr></thead><tbody>${rows.slice((page-1)*20,page*20).map(r=>`<tr><td><strong>${esc(r.school)}</strong><span class="muted">历史参考 · 未核实</span></td><td>${esc([r.department,r.role,r.field].filter(Boolean).join(' · ').slice(0,150))}</td><td><span class="muted">${esc(r.source)}</span></td><td><button data-ref="${esc(r.id)}">查看原记录</button> <button data-copy="${esc(r.id)}">建立申请</button></td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<div class="empty">没有匹配的参考记录</div>'}<div class="pager"><span>共 ${rows.length} 条 · 第 ${page} / ${pages} 页</span><div><button id="prev" ${page<=1?'disabled':''}>上一页</button> <button id="next" ${page>=pages?'disabled':''}>下一页</button></div></div>`;}
function feedView(){const keywords=state.keywords.split(/[\s,，]+/).filter(Boolean);const rows=feed.items.filter(x=>!state.hidden.includes(x.id)&&matches(x)&&(!filter||(filter==='匹配我的关键词'?keywords.some(k=>x.title.toLowerCase().includes(k.toLowerCase())):filter==='已截止'?x.status==='已截止':(x.jobType||'性质待核实')===filter))).sort((a,b)=>b.firstSeenAt.localeCompare(a.firstSeenAt));return `<div class="panel"><div class="panel-head"><div><h2>从招聘来源发现新线索</h2><div class="muted">${feed.lastCompletedAt?'最近检查：'+esc(new Date(feed.lastCompletedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})):'尚无检查记录'} · ${online?'本地服务已连接':snapshot?'公开招聘快照':'离线模式'}</div></div><button class="primary" id="scan" ${!online||feed.running?'disabled':''}>${feed.running?'正在检查…':'立即检查'}</button></div><p class="muted">首次读取会收录页面上现有的招聘标题，可能包含旧公告；“首次发现”是系统发现时间。需要登录、动态加载、验证码的站点需手动查看。原文核实后再加入申请。</p><button class="subtle" data-go="settings">管理来源与关键词 →</button></div>`+toolbar(['匹配我的关键词','学术岗位','博士后','行政或辅助','性质待核实','混合岗位','已截止'],'搜索招聘标题或来源…')+`<div class="cards">${rows.map(x=>`<article class="card"><span class="pill warn">${esc(x.jobType||'性质待核实')} · ${esc(x.status||'有效性待核实')}</span><h3>${esc(x.title)}</h3><p>${esc(x.sourceName)}<br>发布 ${esc(x.publishedAt||'未核实')} · 首次发现 ${esc(x.firstSeenAt.slice(0,10))}<br>截止 ${esc(x.deadline||'未核实')} · ${esc(x.dateStatus||'待核实')}<br>${esc(x.detailStatus==='读取失败'?'原文读取失败：'+x.detailError:x.verification)}</p><div class="card-actions">${link(x.url)}<button data-feed-add="${esc(x.id)}">建立申请</button><button class="subtle" data-hide="${esc(x.id)}">隐藏</button></div></article>`).join('')}</div>${rows.length?'':`<div class="panel empty"><strong>${feed.running?'正在读取启用的来源':'暂无符合条件的线索'}</strong>${online?'检查来源状态，或手动新增申请。':'公开快照可直接浏览；实时扫描需本地服务或定时工作流。'}</div>`}<section class="panel section-gap"><h2>各来源检查结果</h2>${feed.runs.length?feed.runs.map(r=>`<div class="source-row"><div><h3>${esc(r.name)}</h3><p>${esc(r.message)}</p></div><span class="pill ${r.status==='读取失败'?'red':'warn'}">${esc(r.status)} · 新增 ${r.added}</span></div>`).join(''):'<p class="muted">运行检查后会显示成功、失败或无法提取的具体情况。</p>'}</section>`;}
function resourcesView(){return `<div class="notice">原始文件包含他人的投递过程、私人评价和旧年度资料，保留作私人参考。待遇和院系评价需要你另行核实。</div><div class="grid"><section class="panel"><h2>模板与求职经验</h2>${seed.resources.map(r=>`<div class="resource"><span>${esc(r.title)}<small class="muted"> · ${esc(r.group)}</small></span><a href="${esc(r.path)}" download>下载</a></div>`).join('')}</section><section class="panel links-list"><h2>原文入口</h2><p class="muted">来自《学术招聘大全》，链接和内容可能已过期。</p>${seed.links.map(x=>link(x.url,x.title||x.url)).join('')}</section></div>`;}
function settings(){return `<section class="panel"><div class="panel-head"><h2>招聘来源</h2><span class="pill">启动时 + 每 6 小时</span></div><p class="muted">仅在 START.cmd 运行且电脑联网时检查；关机后不会继续，也不补跑关机期间的检查。已配置社科院及人大官方入口，能否读取以检查结果为准。Pages 展示定时工作流生成的公开快照。最多同时启用 20 个来源。</p><div id="sources">${sources.length?sources.map(s=>`<div class="source-row"><input type="checkbox" aria-label="启用 ${esc(s.name)}" data-source="${esc(s.id)}" ${s.enabled?'checked':''} ${!online||feed.running?'disabled':''}><div><h3>${esc(s.name)}</h3><p>${link(s.url,s.url)}</p></div><button data-remove-source="${esc(s.id)}" ${!online||feed.running?'disabled':''}>移除</button></div>`).join(''):'<p class="muted">连接本地服务后显示来源配置。</p>'}</div><form id="source-form" class="source-add"><input name="name" placeholder="学校 / 来源名称" required aria-label="来源名称"><input name="url" type="url" placeholder="学校、政府或 AEA 招聘列表网址" required aria-label="来源网址"><button ${!online||feed.running?'disabled':''}>添加来源</button></form><div class="card-actions"><button id="save-sources" ${!online||feed.running?'disabled':''}>保存来源设置</button><span class="muted">${dirtySources?'有未保存的修改':'支持学校、政府、AEA 及已核实社科院官方域名；请添加招聘列表页。'}</span></div></section><section class="panel"><h2>我的关键词</h2><p class="muted">用空格分隔。用于招聘线索页的“匹配我的关键词”，不会把其他标题永久删除。</p><div class="toolbar"><input id="keywords" aria-label="研究方向关键词" value="${esc(state.keywords)}"><button id="save-keywords">保存关键词</button></div></section><section class="panel"><h2>数据与备份</h2><p class="muted">个人申请保存在当前浏览器；更换浏览器、换设备或清理网站数据前请导出 JSON 备份。备份含日程、咨询记录、材料勾选、历史进度和备注。JSON 导入将合并记录，相同编号以备份为准；CSV 导入跳过重复目标。来源配置和招聘线索保存在运行文件夹的 data 内。</p><div class="toolbar"><button data-backup>导出 JSON 备份</button><button data-import>导入 JSON / CSV</button><button id="csv-template">下载 CSV 模板</button><button id="unhide">恢复隐藏的线索（${state.hidden.length}）</button></div><p class="muted">已有 Excel 模板的 239 条参考已内置。后续表格请按 CSV 模板整理，另存为 UTF-8 CSV 后导入；本页不直接解析任意 Excel 排版。</p></section>`;}
function render(){const [title,sub]=meta[tab];$('#page-title').textContent=title;$('#page-subtitle').textContent=sub;document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===tab));$('#job-count').textContent=state.jobs.length;$('#feed-count').textContent=feed.items.filter(x=>!state.hidden.includes(x.id)).length;$('#mode-note').textContent=online?'本地私人工作台 · 个人记录在本浏览器保存，招聘监测在本地运行。':'离线阅读模式 · 可以整理投递；自动收集需运行 START.cmd，并访问 http://127.0.0.1:8787。';$('#main-content').innerHTML=({overview,consultations,conferences,jobs,feed:feedView,references,resources:resourcesView,settings})[tab]();bind();}
function bind(){
 $('#search')?.addEventListener('input',e=>{const pos=e.target.selectionStart;query=e.target.value;page=1;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);});
 $('#filter')?.addEventListener('change',e=>{filter=e.target.value;page=1;render();});
 $('#prev')?.addEventListener('click',()=>{page--;render();});$('#next')?.addEventListener('click',()=>{page++;render();});
 $('#export-csv')?.addEventListener('click',()=>download('我的投递-'+C.today()+'.csv',C.csv([['学校','学院','岗位','城市','研究方向','招聘链接','截止日期','阶段','投递日期','面试日期','跟进日期','推荐信截止','推荐信方式','推荐信状态','备注'],...state.jobs.map(j=>['school','department','role','city','field','url','deadline','stage','appliedAt','interviewAt','followupAt','referenceDue','referenceMethod','referenceState','notes'].map(k=>j[k]))]),'text/csv;charset=utf-8'));
 $('#csv-template')?.addEventListener('click',()=>download('求职导入模板.csv',C.csv([['学校','学院','岗位','城市','研究方向','招聘链接','截止日期','阶段','投递日期','面试日期','跟进日期','备注']]),'text/csv;charset=utf-8'));
 $('#unhide')?.addEventListener('click',()=>{if(persist({...state,hidden:[]})){toast('已恢复全部线索');render();}});
 $('#save-keywords')?.addEventListener('click',()=>{if(persist({...state,keywords:$('#keywords').value.trim()}))toast('关键词已保存');});
 $('#scan')?.addEventListener('click',async()=>{try{await api('/api/scan',{method:'POST',body:'{}'});feed.running=true;render();poll();}catch(e){toast('检查失败：'+e.message);}});
 $('#source-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),url=C.safeURL(f.get('url'));if(!url)return toast('请输入有效网址');if(sources.some(x=>x.url===url))return toast('该来源已经存在');sources.push({id:C.id(),name:f.get('name').trim(),url,enabled:true});dirtySources=true;render();});
 document.querySelectorAll('[data-source]').forEach(e=>e.addEventListener('change',()=>{sources.find(s=>s.id===e.dataset.source).enabled=e.checked;dirtySources=true;}));
 $('#save-sources')?.addEventListener('click',async()=>{try{await api('/api/sources',{method:'POST',body:JSON.stringify(sources)});dirtySources=false;toast('来源设置已保存；下次检查生效');render();}catch(e){toast('保存失败：'+e.message);}});
}
function openEditor(job){editing=job?structuredClone(job):C.newJob();const f=$('#job-form');f.reset();for(const el of f.elements){if(el.name&&el.name!=='material'){if(el.type==='checkbox')el.checked=editing[el.name]===true;else el.value=editing[el.name]??'';}}
 f.querySelectorAll('[name="material"]').forEach(e=>e.checked=editing.materials.includes(e.value));$('#editor-title').textContent=state.jobs.some(j=>j.id===editing.id)?'编辑申请':'新建申请';$('#delete-job').hidden=!state.jobs.some(j=>j.id===editing.id);$('#form-error').textContent='';$('#job-history').innerHTML='<strong>来源：</strong>'+esc(editing.source)+(editing.history.length?'<br><strong>进度记录：</strong><br>'+editing.history.slice(-8).map(x=>esc(x.at.slice(0,10)+' · '+x.text)).join('<br>'):'');$('#editor').showModal();}
function fromReference(id){const r=seed.references.find(x=>x.id===id);if(!r)return;const next=C.newJob({school:r.school,department:r.department,role:r.role==='待核实'||r.role==='推荐信提交参考'?'':r.role,field:r.field,url:r.urls[0]||'',source:r.source});const old=state.jobs.find(j=>C.duplicate(j,next));if(old){toast('已有相同目标，已打开原申请');openEditor(old);}else openEditor(next);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.tab)switchTab(d.tab);if(d.go)switchTab(d.go);if('close'in d)b.closest('dialog').close();if('backup'in d)exportBackup();if('import'in d)$('#import-file').click();
 if(d.edit)openEditor(state.jobs.find(j=>j.id===d.edit));if(d.copy)fromReference(d.copy);
 if(d.ref){const r=seed.references.find(x=>x.id===d.ref);$('#detail-body').innerHTML=`<p class="pill warn">历史原记录，当前有效性未核实</p><h3>${esc(r.school)}</h3><p class="muted">${esc(r.source)}</p><pre>${esc(r.raw)}</pre><div class="links-list">${r.urls.map(u=>link(u,u)).join('')}</div>`;$('#detail').showModal();}
 if(d.feedAdd){const r=feed.items.find(x=>x.id===d.feedAdd),old=state.jobs.find(j=>j.source===r.url);if(old){toast('该线索已有申请');openEditor(old);}else openEditor(C.newJob({school:r.sourceName.split(' · ')[0],role:r.title,url:r.url,source:r.url}));}
 if(d.hide){if(persist({...state,hidden:[...new Set([...state.hidden,d.hide])]}))render();}
 if(d.removeSource){sources=sources.filter(x=>x.id!==d.removeSource);dirtySources=true;render();}
});
$('#add-job').onclick=()=>openEditor();$('#side-backup').onclick=exportBackup;
$('#stage-options').innerHTML=C.stages.map(s=>`<option>${s}</option>`).join('');$('#material-options').innerHTML=C.materials.map(m=>`<label><input name="material" type="checkbox" value="${esc(m)}">${esc(m)}</label>`).join('');
$('#job-form').addEventListener('submit',e=>{e.preventDefault();try{const f=new FormData(e.target),x={...editing,...Object.fromEntries(f),materials:f.getAll('material'),verified:f.has('verified')};const j=C.validateJob(x);const old=state.jobs.find(r=>r.id===j.id);j.history=[...j.history,{at:new Date().toISOString(),text:old?(old.stage===j.stage?'更新申请信息':old.stage+' → '+j.stage):'建立申请'}];const jobs=old?state.jobs.map(r=>r.id===j.id?j:r):[...state.jobs,j];if(persist({...state,jobs})){$('#editor').close();toast('申请已保存');render();}}catch(err){$('#form-error').textContent=err.message;}});
$('#delete-job').onclick=()=>{if(confirm('删除这条申请？建议先导出备份。')){if(persist({...state,jobs:state.jobs.filter(j=>j.id!==editing.id)})){$('#editor').close();render();toast('申请已删除');}}};
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20*1024*1024)throw Error('文件超过 20 MB');const text=await file.text();let next,count=0;if(file.name.toLowerCase().endsWith('.json')){const imported=C.backup(text);if(!confirm(`导入 ${imported.jobs.length} 条记录？相同编号以备份内容为准，其余现有记录保留。`))return;const map=new Map(state.jobs.map(j=>[j.id,j]));for(const j of imported.jobs)map.set(j.id,j);next={...state,jobs:[...map.values()],events:mergePlanner(state.events,imported.events),consultations:mergePlanner(state.consultations,imported.consultations),hidden:[...new Set([...state.hidden,...imported.hidden])],keywords:imported.keywords||state.keywords};count=imported.jobs.length;}else if(file.name.toLowerCase().endsWith('.csv')){const imported=C.importCSV(text),jobs=[...state.jobs];for(const j of imported){if(!jobs.some(r=>C.duplicate(r,j))){jobs.push(j);count++;}}next={...state,jobs};}else throw Error('请选择 JSON 或 UTF-8 CSV 文件');if(persist(next)){toast('导入完成：'+count+' 条');switchTab('jobs');}}catch(err){toast('未导入：'+err.message);}});
async function api(url,options={}){const res=await fetch(url,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...options.headers}});const body=await res.json();if(!res.ok)throw Error(body.error||'服务不可用');return body;}
let polling=false;async function poll(){if(polling||location.protocol==='file:')return;polling=true;try{const wasRunning=feed.running;feed=await api(online?'/api/feed':'public/feed.json');snapshot=!online;$('#feed-count').textContent=feed.items.filter(x=>!state.hidden.includes(x.id)).length;if(['feed','overview'].includes(tab)||(tab==='settings'&&wasRunning!==feed.running))render();if(feed.running)setTimeout(()=>{polling=false;poll();},2000);else polling=false;}catch(e){online=false;polling=false;if(['feed'].includes(tab))render();}}
const conferenceList=(window.RADAR_CONFERENCES||[]).filter(x=>['conference','journal'].includes(x.category));
let scheduleRange='week',plannerKind='events',plannerEditing=null;
function mergePlanner(a=[],b=[]){return [...new Map([...a,...b].map(x=>[x.id,x])).values()];}
function agenda(){return [...C.tasks(state.jobs,C.today(),Infinity).map(t=>({...t,title:t.school,label:t.label,kind:'job'})),...(state.events||[]).filter(x=>!x.done).map(x=>({...x,label:x.category||'日程',days:C.days(x.date),kind:'event'})),...(state.consultations||[]).filter(x=>x.followupAt).map(x=>({id:x.id,title:x.person,date:x.followupAt,label:x.nextAction||'咨询后续跟进',days:C.days(x.followupAt),kind:'consultation'}))].sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||''));}
function agendaRow(t){return `<div class="task"><span class="task-date">${esc(t.date.slice(5))}<small>${esc(t.time||'')}</small></span><div class="grow"><strong>${esc(t.title)}</strong><div class="muted">${esc(t.label)}</div></div><span class="pill ${t.days<0?'red':t.days===0?'warn':''}">${t.days<0?'逾期 '+(-t.days)+' 天':t.days===0?'今天':t.days+' 天后'}</span>${t.kind==='job'?`<button data-edit="${esc(t.id)}">查看</button>`:`<button data-plan-edit="${esc(t.id)}" data-kind="${t.kind==='event'?'events':'consultations'}">查看</button>`}${t.kind==='event'?`<button class="subtle" data-plan-done="${esc(t.id)}">完成</button>`:''}</div>`;}
function overview(){const all=agenda(),n=scheduleRange==='today'?0:scheduleRange==='week'?7:30,rows=all.filter(t=>scheduleRange==='all'||(t.days<=n&&(scheduleRange!=='today'||t.days===0)));const due=all.filter(t=>t.days<0).length;return `<div class="stats">${[['今天',all.filter(t=>t.days===0).length,'今天需要处理'],['未来七天',all.filter(t=>t.days>=0&&t.days<=7).length,'安排与截止'],['待跟进',due,'已逾期事项'],['进行中申请',state.jobs.filter(x=>!['已结束','已获 Offer'].includes(x.stage)).length,'求职进展']].map(([a,b,c])=>`<div class="stat"><small>${a}</small><strong>${b}</strong><em>${c}</em></div>`).join('')}</div><div class="toolbar range-tabs">${[['today','今天'],['week','未来七天'],['month','未来三十天'],['all','全部待办']].map(([v,l])=>`<button data-range="${v}" class="${v===scheduleRange?'primary':''}">${l}</button>`).join('')}<span class="spacer"></span><button class="primary" data-plan-new="events">＋ 新建日程</button><button data-plan-new="consultations">＋ 记一次咨询</button></div><div class="grid"><section class="panel"><div class="panel-head"><h2>日程与跟进</h2><span class="pill">${rows.length} 项</span></div>${rows.length?rows.map(agendaRow).join(''):'<div class="empty"><strong>这段时间暂无安排</strong>新建日程，或填写申请的截止日、面试和跟进日期。</div>'}<details class="completed"><summary>已完成的日程（${(state.events||[]).filter(x=>x.done).length}）</summary>${(state.events||[]).filter(x=>x.done).map(x=>`<div class="task"><span>${esc(x.date)}</span><strong class="grow">${esc(x.title)}</strong><button data-plan-edit="${esc(x.id)}" data-kind="events">编辑</button><button data-plan-done="${esc(x.id)}">恢复</button></div>`).join('')}</details></section><div><section class="panel"><div class="panel-head"><h2>近期征稿</h2><button class="subtle" data-go="conferences">全部 →</button></div>${conferenceList.filter(x=>C.validDate(x.deadline)&&C.days(x.deadline)>=0&&x.status!=='closed').sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,4).map(x=>`<div class="upcoming"><span class="pill">${esc(x.deadline)}</span><h3>${esc(x.title)}</h3><button data-conference-plan="${esc(x.id)}">加入日程</button></div>`).join('')||'<p class="muted">暂无仍开放的征稿记录。</p>'}<p class="muted">沿用已有快照，最新要求请查看通知。</p></section><section class="panel"><div class="panel-head"><h2>最近咨询</h2><button class="subtle" data-go="consultations">全部 →</button></div>${[...(state.consultations||[])].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(x=>`<div class="upcoming"><h3>${esc(x.person)} <small class="muted">${esc(x.date)}</small></h3><p>${esc(x.topic||x.institution)}</p><button data-plan-edit="${esc(x.id)}" data-kind="consultations">查看记录</button></div>`).join('')||'<p class="muted">记录一次交流，保留要点与下一步。</p>'}</section></div></div>`;}
function consultations(){const rows=(state.consultations||[]).filter(matches).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="toolbar"><button class="primary" data-plan-new="consultations">＋ 新建咨询记录</button></div>`+toolbar(null,'搜索咨询对象、单位、主题或原始记录…')+`<div class="cards">${rows.map(x=>`<article class="card"><div class="panel-head"><h3>${esc(x.person)}</h3><span class="pill">${esc(x.date||'日期未填')}</span></div><p class="muted">${esc(x.institution)}</p><h3>${esc(x.topic)}</h3><p class="record-text">${esc(x.notes)}</p>${x.nextAction?`<p><strong>下一步：</strong>${esc(x.nextAction)}</p>`:''}${x.followupAt?`<p class="muted">跟进日期 ${esc(x.followupAt)}</p>`:''}<button data-plan-edit="${esc(x.id)}" data-kind="consultations">编辑 / 跟进</button></article>`).join('')}</div>${rows.length?'':'<div class="panel empty"><strong>把一次有用的交流记下来</strong>记录咨询对象、日期和原始要点；需要跟进时填写下一步与跟进日期。</div>'}`;}
function conferences(){const rows=conferenceList.filter(matches).filter(x=>!filter||(filter==='仍可投稿'?C.validDate(x.deadline)&&C.days(x.deadline)>=0&&x.status!=='closed':filter==='重点关注'?x.priority==='core':C.validDate(x.deadline)&&C.days(x.deadline)<0||x.status==='closed')).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));return `<div class="notice">会议信息沿用已有快照；加入日程前请核对原通知的日期和要求。<a href="conferences.html">打开完整会议页 ↗</a></div>`+toolbar(['仍可投稿','重点关注','历史记录'],'搜索会议、机构、主题或期刊…')+`<div class="cards">${rows.map(x=>`<article class="card"><span class="pill ${C.days(x.deadline)<0?'':'warn'}">${esc(x.deadline||'截止待确认')}</span><h3>${esc(x.title)}</h3><p>${esc(x.location)} · ${esc(x.meetingDates)}</p><p class="muted">${esc(x.relationship)}</p><p>${esc(x.journals.join(' · ')||'未列明期刊支持')}</p><p class="muted">${esc(x.deadlineNote)}</p><div class="card-actions">${link(x.noticeUrl,'查看通知 ↗')}<button data-conference-plan="${esc(x.id)}">加入日程</button></div></article>`).join('')}</div>${rows.length?'':'<div class="panel empty">没有匹配的会议</div>'}`;}
function plannerOpen(kind,item={}){plannerKind=kind;plannerEditing={id:C.id(),...item};const event=kind==='events',fields=event?[['title','日程名称 *','text'],['date','日期 *','date'],['time','时间','time'],['category','类别','category'],['jobId','关联申请','job'],['notes','备注与准备事项','textarea']]:[['person','咨询对象 *','text'],['date','咨询日期','date'],['institution','单位 / 机构','text'],['topic','交流主题','text'],['jobId','关联申请','job'],['notes','原始要点 / 交流记录','textarea'],['nextAction','下一步','text'],['followupAt','跟进日期','date']];$('#planner-title').textContent=event?'日程安排':'咨询记录';$('#planner-fields').innerHTML=fields.map(([k,l,t])=>`<label class="${t==='textarea'?'wide':''}">${l}${t==='textarea'?`<textarea name="${k}" rows="5">${esc(item[k])}</textarea>`:t==='job'?`<select name="${k}"><option value="">不关联</option>${state.jobs.map(j=>`<option value="${esc(j.id)}" ${j.id===item[k]?'selected':''}>${esc(j.school+' · '+j.role)}</option>`).join('')}</select>`:t==='category'?`<select name="${k}">${['求职','会议投稿','参会','研究','咨询','其他'].map(v=>`<option ${v===item[k]?'selected':''}>${v}</option>`).join('')}</select>`:`<input name="${k}" type="${t}" value="${esc(item[k])}" ${k==='title'||k==='person'||event&&k==='date'?'required':''} maxlength="20000">`}</label>`).join('');$('#planner-delete').hidden=!(state[kind]||[]).some(x=>x.id===item.id);$('#planner-error').textContent='';$('#planner-editor').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.range){scheduleRange=d.range;render();}if(d.planNew)plannerOpen(d.planNew);if(d.planEdit)plannerOpen(d.kind,(state[d.kind]||[]).find(x=>x.id===d.planEdit));if(d.planDone){if(persist({...state,events:(state.events||[]).map(x=>x.id===d.planDone?{...x,done:!x.done}:x)}))render();}if(d.conferencePlan){const x=conferenceList.find(x=>x.id===d.conferencePlan);const old=(state.events||[]).find(y=>y.conferenceId===x.id);plannerOpen('events',old||{title:x.title+' · 投稿准备',date:x.deadline||'',category:'会议投稿',conferenceId:x.id,notes:[x.material,x.deadlineNote,x.noticeUrl].filter(Boolean).join('\n')});}});
$('#planner-form').addEventListener('submit',e=>{e.preventDefault();try{const item=C.plannerRows([{...plannerEditing,...Object.fromEntries(new FormData(e.target))}],plannerKind)[0];const next={...state,[plannerKind]:mergePlanner(state[plannerKind], [item])};if(persist(next)){$('#planner-editor').close();render();toast('记录已保存');}}catch(err){$('#planner-error').textContent=err.message;}});
$('#planner-delete').onclick=()=>{if(confirm('删除这条记录？')){if(persist({...state,[plannerKind]:(state[plannerKind]||[]).filter(x=>x.id!==plannerEditing.id)})){$('#planner-editor').close();render();}}};

$('#today').textContent=C.today()+' · PERSONAL WORKSPACE';render();
if(location.protocol!=='file:'){
 async function loadFeed(){
  try{if(!['localhost','127.0.0.1'].includes(location.hostname))throw Error('static');
   [feed,sources]=await Promise.all([api('/api/feed'),api('/api/sources')]);online=true;
  }catch{try{[feed,sources]=await Promise.all([api('public/feed.json'),api('public/sources.json')]);snapshot=true;}catch{}}
  render();if(feed.running)poll();
 }
 loadFeed();setInterval(()=>{if(!document.hidden)poll();},60000);
}
